import unittest
from aoc_2024.solutions.day_08 import part_one, part_two


test_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split(
    "\n"
)


class Test(unittest.TestCase):
    def test_part_one(self):
        self.assertEqual(part_one(test_input), 14)

    def test_part_two(self):
        self.assertEqual(part_two(test_input), 34)


def main():
    unittest.main()
